version: "3.5"

services:
  postgresql:
    image: postgres:13.3
    env_file:
      - env.d/postgresql

  grafana:
    image: grafana/grafana:8.0.3
    ports:
      - 3000:3000
    user: "${DOCKER_USER:-1000}"
    volumes:
      - ./etc/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./src/plugins:/var/lib/grafana/plugins/potsie
      - ./var/lib/grafana/dashboards:/var/lib/grafana/dashboards
    env_file:
      - env.d/grafana
    depends_on:
      - postgresql
    networks:
      - default
      - potsie

  app:
    build:
      context: .
    image: potsie:development
    env_file:
      - env.d/app
    user: "${DOCKER_USER:-1000}"
    volumes:
      - ./src/dashboards:/app/dashboards
      - ./src/plugins:/app/plugins
      - ./var/lib/grafana/dashboards:/var/lib/grafana/dashboards

  node:
    image: node:14
    user: "${DOCKER_USER:-1000}"
    # We must run node with a /home because yarn tries to write to ~/.yarnrc.
    # If the ID of our host user (with which we run the container) does not
    # exist in the container (e.g. 1000 exists but 1009 does not exist by
    # default), then yarn will try to write to "/.yarnrc" at the root of the
    # system and will fail with a permission error.
    environment:
      - HOME=/tmp
    working_dir: /src/plugins
    volumes:
      - ./src/plugins:/src/plugins

  jb:
    image: potsie:builder
    build:
      context: .
      target: builder
    volumes:
      - ./jsonnetfile.json:/go/jsonnetfile.json
      - ./jsonnetfile.lock.json:/go/jsonnetfile.lock.json
    entrypoint: jb

  dockerize:
    image: jwilder/dockerize

networks:
  potsie:
    name: potsie
    driver: bridge
