apiVersion: 1

datasources:
  - name: lrs
    type: elasticsearch
    editable: false
    access: proxy
    database: "statements-marsha-*"
    url: http://elasticsearch:9200
    jsonData:
      esVersion: 70
      timeField: "timestamp"
