// This file is needed because it is used by vscode and other tools that
// call `jest` directly.  However, unless you are doing anything special
// do not edit this file

const standard = require('@grafana/toolkit/src/config/jest.plugin.config');

// This process will use the same config that `yarn test` is using
const config = standard.jestConfig()
config.globals['ts-jest'].tsconfig = config.globals['ts-jest'].tsConfig;
delete config.globals['ts-jest'].tsConfig;
config.transform = { "\\.(ts|tsx)$": "ts-jest" }

module.exports = config;
